language: r
sudo: required
group: deprecated-2017Q4
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

r_binary_packages:
  - rgdal
  - rgeos

## Set up the matrix of different runs
env:
  matrix:
  - r: release
    not_cran: true
    r_check_args: "--no-manual"
  - r: release
    not_cran: false
    r_check_args: "--no-manual --as--cran"

script:
  - |
    R CMD build .
    travis_wait 20 R CMD check bomrang*tar.gz

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov()'
