language: r
dist: trusty
sudo: required
cache: packages

apt_packages:
  - libudunits2-dev

r:
  - oldrel
  - release

r_packages:
  - rgdal
  - raster
  - rgeos

r_github_packages:
  - jimhester/covr

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos++-dev libgdal-dev

compiler:
  - clang


env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
      - BOOTSTRAP_LATEX=""

script:
  - |
    R CMD build .
    travis_wait 20 R CMD check bomrang*tar.gz

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov()'
