language: r
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
r_binary_packages:
   - Rcpp
   - stringi
   - dplyr
   - readr
   - rgdal
   - rgeos
   - raster
   - tidyr
   - purrr
   - roxygen2
   - xml2
   - ggplot2

## Set up the matrix of different runs
env:
  matrix:
  - r: release
    not_cran: true
    r_check_args: "--no-manual"
  - r: release
    not_cran: false
    r_check_args: "--no-manual --as--cran"

script:
  - |
    R CMD build .
    travis_wait 40 R CMD check bomrang*tar.gz

after_failure:
  - R -e 'devtools::test(filter = "bulletin")'
  - R -e 'devtools::test(filter = "pr.cis")'
  # What error is being produced
  - R -e 'httr::http_error("ftp://ftp.bom.gov.au/anon/gen/fwo/IDN11060.xml")'
  - R -e 'httr::HEAD("ftp://ftp.bom.gov.au/anon/gen/fwo/IDN11060.xml")'
  - R -e 'xml2::read_xml("ftp://ftp.bom.gov.au/anon/gen/fwo/IDN11060.xml")'
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov()'
